add arg to the config_schema.yml file for gzipped and hook up in run_stardis
tardis-sn/stardis pull request #116
Opened 2023-08-09 20:44 UTC by jvshields

Allows the config to take a gzipped argument in model and passes that to the model reader.

This allows the config to point to any plane-parallel model obtained from https://marcs.oreme.org/

2023-08-09 20:56 UTC, sonachitchyan approved these changes

2023-08-10 18:19 UTC, andrewfullard requested changes

2023-08-10 18:19 UTC, andrewfullard commented on stardis/base.py
>          # FIX THIS BY ADDING AN OPTIONAL GZIPPED ARGUMENT TO THE CONFIG
Remove comment, it's done!

2023-08-11 16:43 UTC, andrewfullard approved these changes

2023-08-11 18:05 UTC, sonachitchyan approved these changes

2023-08-11 18:06 UTC, merged